package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.CheckTemplate;

public interface CheckTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checktemplate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checktemplate
     *
     * @mbggenerated
     */
    int insert(CheckTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checktemplate
     *
     * @mbggenerated
     */
    int insertSelective(CheckTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checktemplate
     *
     * @mbggenerated
     */
    CheckTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checktemplate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CheckTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checktemplate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CheckTemplate record);
}