package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.CheckRelation;

public interface CheckRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrelation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrelation
     *
     * @mbggenerated
     */
    int insert(CheckRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrelation
     *
     * @mbggenerated
     */
    int insertSelective(CheckRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrelation
     *
     * @mbggenerated
     */
    CheckRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CheckRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CheckRelation record);
}