package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.CheckApply;

public interface CheckApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkapply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkapply
     *
     * @mbggenerated
     */
    int insert(CheckApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkapply
     *
     * @mbggenerated
     */
    int insertSelective(CheckApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkapply
     *
     * @mbggenerated
     */
    CheckApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkapply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CheckApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkapply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CheckApply record);
}