package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.CheckApply;

public interface CheckApplyMapper {

    int deleteByPrimaryKey(Integer id);

    int insert(CheckApply record);

    int insertSelective(CheckApply record);

    CheckApply selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(CheckApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkapply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CheckApply record);

    int updateState(Integer[] ids);

    int updateRefundState(Integer[] ids);
}