package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.Disecategory;

import java.util.List;

public interface DisecategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disecategory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disecategory
     *
     * @mbggenerated
     */
    int insert(Disecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disecategory
     *
     * @mbggenerated
     */
    int insertSelective(Disecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disecategory
     *
     * @mbggenerated
     */
    Disecategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disecategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Disecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disecategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Disecategory record);

    int delManyDisecategory(Integer[] ids);

    int delDisecategory(Integer id);

    List<Disecategory> searchDisecategoryBynameOrcode(String keywords);
}