package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.HerbalPrescription;

public interface HerbalPrescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbalprescription
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbalprescription
     *
     * @mbggenerated
     */
    int insert(HerbalPrescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbalprescription
     *
     * @mbggenerated
     */
    int insertSelective(HerbalPrescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbalprescription
     *
     * @mbggenerated
     */
    HerbalPrescription selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbalprescription
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HerbalPrescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbalprescription
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HerbalPrescription record);
}