package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.HerbalDetailed;

public interface HerbalDetailedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaldetailed
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaldetailed
     *
     * @mbggenerated
     */
    int insert(HerbalDetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaldetailed
     *
     * @mbggenerated
     */
    int insertSelective(HerbalDetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaldetailed
     *
     * @mbggenerated
     */
    HerbalDetailed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaldetailed
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HerbalDetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaldetailed
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HerbalDetailed record);
}