package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.HerbalTemplate;

public interface HerbalTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaltemplate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaltemplate
     *
     * @mbggenerated
     */
    int insert(HerbalTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaltemplate
     *
     * @mbggenerated
     */
    int insertSelective(HerbalTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaltemplate
     *
     * @mbggenerated
     */
    HerbalTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaltemplate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HerbalTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaltemplate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HerbalTemplate record);
}