package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.Invoice;

import java.util.List;

public interface InvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbggenerated
     */
    int insert(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbggenerated
     */
    int insertSelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbggenerated
     */
    Invoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Invoice record);

    int updateFlogHeavily(String id);


    int updateRepBill(String id);

    Invoice searchBeginInvoiceNum(String beginTime, String endTime);

    Invoice searchEndInvoiceNum(String beginTime, String endTime);

    List<Invoice> searchBad(String beginTime, String endTime);

    List<Invoice> searchRepeat(String beginTime, String endTime);

    Invoice searchCash(String beginTime, String endTime);

    Invoice searchOther(String beginTime, String endTime);
}