package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.MedicalDisease;

public interface MedicalDiseaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicaldisease
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicaldisease
     *
     * @mbggenerated
     */
    int insert(MedicalDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicaldisease
     *
     * @mbggenerated
     */
    int insertSelective(MedicalDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicaldisease
     *
     * @mbggenerated
     */
    MedicalDisease selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicaldisease
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MedicalDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicaldisease
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MedicalDisease record);
}