package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.Prescription;

public interface PrescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    int insert(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    int insertSelective(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    Prescription selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Prescription record);
}