package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.PrescriptionDetailed;

public interface PrescriptionDetailedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescriptiondetailed
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescriptiondetailed
     *
     * @mbggenerated
     */
    int insert(PrescriptionDetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescriptiondetailed
     *
     * @mbggenerated
     */
    int insertSelective(PrescriptionDetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescriptiondetailed
     *
     * @mbggenerated
     */
    PrescriptionDetailed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescriptiondetailed
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrescriptionDetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescriptiondetailed
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrescriptionDetailed record);
}