package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.Registlevel;

import java.util.List;

public interface RegistlevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbggenerated
     */
    int insert(Registlevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbggenerated
     */
    int insertSelective(Registlevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbggenerated
     */
    Registlevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Registlevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Registlevel record);

    List<Registlevel> registService();

    int delManyRegist(Integer[] ids);

    List<Registlevel> searchRegistByRegistnameOrRegistcode(String keywords);

    int delRegist(Integer id);
}