package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.Constantitem;
import org.neuedu.hisjava.model.Invoice;
import org.neuedu.hisjava.model.Register;
import org.neuedu.hisjava.model.Settlecategory;

import java.util.List;

public interface RegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated
     */
    int insert(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated
     */
    int insertSelective(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated
     */
    Register selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Register record);

    List<Constantitem> searchGender();

    List<Constantitem> searchCharge();

    List<Settlecategory> searchSettle();

    Register searchRegister();

    Invoice searchInvoice();

    Register searchPatientInfo(Register register);

    List<Register> searchAllRegister(String casenumber);

    int updateVisitstate(String id);

    Register searchOneRegisterByCasenumber(String casenumber);

    List<Register> searchRegisterByasenumber(String casenumber);
}