package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.Registwork;

public interface RegistworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registwork
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registwork
     *
     * @mbggenerated
     */
    int insert(Registwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registwork
     *
     * @mbggenerated
     */
    int insertSelective(Registwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registwork
     *
     * @mbggenerated
     */
    Registwork selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registwork
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Registwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registwork
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Registwork record);
}