package org.neuedu.hisjava.mapper;

import io.lettuce.core.dynamic.annotation.Param;
import org.neuedu.hisjava.model.Scheduling;

import java.util.List;

public interface SchedulingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbggenerated
     */
    int insert(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbggenerated
     */
    int insertSelective(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbggenerated
     */
    Scheduling selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Scheduling record);

    List<Scheduling> searchScheduing(@Param("startDate") String startDate,@Param("endDate") String endDate);
}