package org.neuedu.hisjava.mapper;

import org.neuedu.hisjava.model.Settlecategory;

import java.util.List;

public interface SettlecategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbggenerated
     */
    int insert(Settlecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbggenerated
     */
    int insertSelective(Settlecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbggenerated
     */
    Settlecategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Settlecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Settlecategory record);

    List<Settlecategory> searchSettlecategoryBynameOrcode(String keywords);

    int delSettlecategory(Integer id);

    int delManySettlecategory(Integer[] ids);
}