package org.neuedu.hisjava.mapper;

import io.lettuce.core.dynamic.annotation.Param;
import org.neuedu.hisjava.model.Constantitem;
import org.neuedu.hisjava.model.User;
import org.neuedu.hisjava.model.UserBean;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    UserBean loadUserByUsername(String username);

    List<User> searchUserByDeptAndRegist(String adddeptvalue, String registvalue);

    List<User> searchUserByUsernameOrRealname(String keywords);


    int delUser(Integer id);

    int delManyUser(Integer[] ids);

    List<Constantitem> searchAllUserName();
}