package org.neuedu.hisjava.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class CheckApply implements Serializable {

    private Integer id;
    private Integer medicalid;
    private Integer registid;
    private Integer itemid;
    private String name;
    private String objective;
    private String position;
    private Integer isurgent;
    private Integer num;
    @JsonFormat(pattern = "yyyy-MM-dd hh:mm:ss",timezone = "Asia/Shanghai")
    private Date creationtime;
    private Integer doctorid;
    private Integer checkoperid;
    private Integer resultoperid;
    private Date checktime;
    private String result;
    private Date resulttime;
    private Integer state;
    private Integer recordtype;

    private Fmeditem fmeditem;
    private Register register;

    public Register getRegister() {
        return register;
    }

    public void setRegister(Register register) {
        this.register = register;
    }

    public Fmeditem getFmeditem() {
        return fmeditem;
    }

    public void setFmeditem(Fmeditem fmeditem) {
        this.fmeditem = fmeditem;
    }

    private static final long serialVersionUID = 1L;
    public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.MedicalID
     *
     * @return the value of checkapply.MedicalID
     *
     * @mbggenerated
     */
    public Integer getMedicalid() {
        return medicalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.MedicalID
     *
     * @param medicalid the value for checkapply.MedicalID
     *
     * @mbggenerated
     */
    public void setMedicalid(Integer medicalid) {
        this.medicalid = medicalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.RegistID
     *
     * @return the value of checkapply.RegistID
     *
     * @mbggenerated
     */
    public Integer getRegistid() {
        return registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.RegistID
     *
     * @param registid the value for checkapply.RegistID
     *
     * @mbggenerated
     */
    public void setRegistid(Integer registid) {
        this.registid = registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.ItemID
     *
     * @return the value of checkapply.ItemID
     *
     * @mbggenerated
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.ItemID
     *
     * @param itemid the value for checkapply.ItemID
     *
     * @mbggenerated
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.Name
     *
     * @return the value of checkapply.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.Name
     *
     * @param name the value for checkapply.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.Objective
     *
     * @return the value of checkapply.Objective
     *
     * @mbggenerated
     */
    public String getObjective() {
        return objective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.Objective
     *
     * @param objective the value for checkapply.Objective
     *
     * @mbggenerated
     */
    public void setObjective(String objective) {
        this.objective = objective == null ? null : objective.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.Position
     *
     * @return the value of checkapply.Position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.Position
     *
     * @param position the value for checkapply.Position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.IsUrgent
     *
     * @return the value of checkapply.IsUrgent
     *
     * @mbggenerated
     */
    public Integer getIsurgent() {
        return isurgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.IsUrgent
     *
     * @param isurgent the value for checkapply.IsUrgent
     *
     * @mbggenerated
     */
    public void setIsurgent(Integer isurgent) {
        this.isurgent = isurgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.Num
     *
     * @return the value of checkapply.Num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.Num
     *
     * @param num the value for checkapply.Num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.CreationTime
     *
     * @return the value of checkapply.CreationTime
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.CreationTime
     *
     * @param creationtime the value for checkapply.CreationTime
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.DoctorID
     *
     * @return the value of checkapply.DoctorID
     *
     * @mbggenerated
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.DoctorID
     *
     * @param doctorid the value for checkapply.DoctorID
     *
     * @mbggenerated
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.CheckOperID
     *
     * @return the value of checkapply.CheckOperID
     *
     * @mbggenerated
     */
    public Integer getCheckoperid() {
        return checkoperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.CheckOperID
     *
     * @param checkoperid the value for checkapply.CheckOperID
     *
     * @mbggenerated
     */
    public void setCheckoperid(Integer checkoperid) {
        this.checkoperid = checkoperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.ResultOperID
     *
     * @return the value of checkapply.ResultOperID
     *
     * @mbggenerated
     */
    public Integer getResultoperid() {
        return resultoperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.ResultOperID
     *
     * @param resultoperid the value for checkapply.ResultOperID
     *
     * @mbggenerated
     */
    public void setResultoperid(Integer resultoperid) {
        this.resultoperid = resultoperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.CheckTime
     *
     * @return the value of checkapply.CheckTime
     *
     * @mbggenerated
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.CheckTime
     *
     * @param checktime the value for checkapply.CheckTime
     *
     * @mbggenerated
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.Result
     *
     * @return the value of checkapply.Result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.Result
     *
     * @param result the value for checkapply.Result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.ResultTime
     *
     * @return the value of checkapply.ResultTime
     *
     * @mbggenerated
     */
    public Date getResulttime() {
        return resulttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.ResultTime
     *
     * @param resulttime the value for checkapply.ResultTime
     *
     * @mbggenerated
     */
    public void setResulttime(Date resulttime) {
        this.resulttime = resulttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.State
     *
     * @return the value of checkapply.State
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.State
     *
     * @param state the value for checkapply.State
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkapply.RecordType
     *
     * @return the value of checkapply.RecordType
     *
     * @mbggenerated
     */
    public Integer getRecordtype() {
        return recordtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkapply.RecordType
     *
     * @param recordtype the value for checkapply.RecordType
     *
     * @mbggenerated
     */
    public void setRecordtype(Integer recordtype) {
        this.recordtype = recordtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkapply
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", medicalid=").append(medicalid);
        sb.append(", registid=").append(registid);
        sb.append(", itemid=").append(itemid);
        sb.append(", name=").append(name);
        sb.append(", objective=").append(objective);
        sb.append(", position=").append(position);
        sb.append(", isurgent=").append(isurgent);
        sb.append(", num=").append(num);
        sb.append(", creationtime=").append(creationtime);
        sb.append(", doctorid=").append(doctorid);
        sb.append(", checkoperid=").append(checkoperid);
        sb.append(", resultoperid=").append(resultoperid);
        sb.append(", checktime=").append(checktime);
        sb.append(", result=").append(result);
        sb.append(", resulttime=").append(resulttime);
        sb.append(", state=").append(state);
        sb.append(", recordtype=").append(recordtype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}