package org.neuedu.hisjava.model;

import org.springframework.cache.annotation.CacheEvict;

import java.io.Serializable;

public class Department implements Serializable {

    private Integer id;
    private String deptcode;
    private String deptname;
    private Constantitem constant;
    private Integer deptcategoryid;
    private Integer depttype;
    private Integer delmark;

    private static final long serialVersionUID = 1L;
    public Integer getId() {
        return id;
    }

    public Constantitem getConstant() {
        return constant;
    }

    public void setConstant(Constantitem constant) {
        this.constant = constant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.ID
     *
     * @param id the value for department.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DeptCode
     *
     * @return the value of department.DeptCode
     *
     * @mbggenerated
     */
    public String getDeptcode() {
        return deptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DeptCode
     *
     * @param deptcode the value for department.DeptCode
     *
     * @mbggenerated
     */
    public void setDeptcode(String deptcode) {
        this.deptcode = deptcode == null ? null : deptcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DeptName
     *
     * @return the value of department.DeptName
     *
     * @mbggenerated
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DeptName
     *
     * @param deptname the value for department.DeptName
     *
     * @mbggenerated
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname == null ? null : deptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DeptCategoryID
     *
     * @return the value of department.DeptCategoryID
     *
     * @mbggenerated
     */
    public Integer getDeptcategoryid() {
        return deptcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DeptCategoryID
     *
     * @param deptcategoryid the value for department.DeptCategoryID
     *
     * @mbggenerated
     */
    public void setDeptcategoryid(Integer deptcategoryid) {
        this.deptcategoryid = deptcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DeptType
     *
     * @return the value of department.DeptType
     *
     * @mbggenerated
     */
    public Integer getDepttype() {
        return depttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DeptType
     *
     * @param depttype the value for department.DeptType
     *
     * @mbggenerated
     */
    public void setDepttype(Integer depttype) {
        this.depttype = depttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DelMark
     *
     * @return the value of department.DelMark
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DelMark
     *
     * @param delmark the value for department.DelMark
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deptcode=").append(deptcode);
        sb.append(", deptname=").append(deptname);
        sb.append(", deptcategoryid=").append(deptcategoryid);
        sb.append(", depttype=").append(depttype);
        sb.append(", delmark=").append(delmark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}