package org.neuedu.hisjava.model;

import java.io.Serializable;

public class Disecategory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disecategory.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disecategory.DicaCode
     *
     * @mbggenerated
     */
    private String dicacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disecategory.DicaName
     *
     * @mbggenerated
     */
    private String dicaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disecategory.SequenceNo
     *
     * @mbggenerated
     */
    private Integer sequenceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disecategory.DicaType
     *
     * @mbggenerated
     */
    private Integer dicatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disecategory.DelMark
     *
     * @mbggenerated
     */
    private Integer delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table disecategory
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disecategory.ID
     *
     * @return the value of disecategory.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disecategory.ID
     *
     * @param id the value for disecategory.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disecategory.DicaCode
     *
     * @return the value of disecategory.DicaCode
     *
     * @mbggenerated
     */
    public String getDicacode() {
        return dicacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disecategory.DicaCode
     *
     * @param dicacode the value for disecategory.DicaCode
     *
     * @mbggenerated
     */
    public void setDicacode(String dicacode) {
        this.dicacode = dicacode == null ? null : dicacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disecategory.DicaName
     *
     * @return the value of disecategory.DicaName
     *
     * @mbggenerated
     */
    public String getDicaname() {
        return dicaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disecategory.DicaName
     *
     * @param dicaname the value for disecategory.DicaName
     *
     * @mbggenerated
     */
    public void setDicaname(String dicaname) {
        this.dicaname = dicaname == null ? null : dicaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disecategory.SequenceNo
     *
     * @return the value of disecategory.SequenceNo
     *
     * @mbggenerated
     */
    public Integer getSequenceno() {
        return sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disecategory.SequenceNo
     *
     * @param sequenceno the value for disecategory.SequenceNo
     *
     * @mbggenerated
     */
    public void setSequenceno(Integer sequenceno) {
        this.sequenceno = sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disecategory.DicaType
     *
     * @return the value of disecategory.DicaType
     *
     * @mbggenerated
     */
    public Integer getDicatype() {
        return dicatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disecategory.DicaType
     *
     * @param dicatype the value for disecategory.DicaType
     *
     * @mbggenerated
     */
    public void setDicatype(Integer dicatype) {
        this.dicatype = dicatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disecategory.DelMark
     *
     * @return the value of disecategory.DelMark
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disecategory.DelMark
     *
     * @param delmark the value for disecategory.DelMark
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disecategory
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dicacode=").append(dicacode);
        sb.append(", dicaname=").append(dicaname);
        sb.append(", sequenceno=").append(sequenceno);
        sb.append(", dicatype=").append(dicatype);
        sb.append(", delmark=").append(delmark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}