package org.neuedu.hisjava.model;

import java.io.Serializable;

public class Disease implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.DiseaseCode
     *
     * @mbggenerated
     */
    private String diseasecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.DiseaseName
     *
     * @mbggenerated
     */
    private String diseasename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.DiseaseICD
     *
     * @mbggenerated
     */
    private String diseaseicd;

    private Disecategory disecategory;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.DiseCategoryID
     *
     * @mbggenerated
     */
    private Integer disecategoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.DelMark
     *
     * @mbggenerated
     */
    private Integer delmark;

    public Disecategory getDisecategory() {
        return disecategory;
    }

    public void setDisecategory(Disecategory disecategory) {
        this.disecategory = disecategory;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table disease
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.ID
     *
     * @return the value of disease.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.ID
     *
     * @param id the value for disease.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.DiseaseCode
     *
     * @return the value of disease.DiseaseCode
     *
     * @mbggenerated
     */
    public String getDiseasecode() {
        return diseasecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.DiseaseCode
     *
     * @param diseasecode the value for disease.DiseaseCode
     *
     * @mbggenerated
     */
    public void setDiseasecode(String diseasecode) {
        this.diseasecode = diseasecode == null ? null : diseasecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.DiseaseName
     *
     * @return the value of disease.DiseaseName
     *
     * @mbggenerated
     */
    public String getDiseasename() {
        return diseasename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.DiseaseName
     *
     * @param diseasename the value for disease.DiseaseName
     *
     * @mbggenerated
     */
    public void setDiseasename(String diseasename) {
        this.diseasename = diseasename == null ? null : diseasename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.DiseaseICD
     *
     * @return the value of disease.DiseaseICD
     *
     * @mbggenerated
     */
    public String getDiseaseicd() {
        return diseaseicd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.DiseaseICD
     *
     * @param diseaseicd the value for disease.DiseaseICD
     *
     * @mbggenerated
     */
    public void setDiseaseicd(String diseaseicd) {
        this.diseaseicd = diseaseicd == null ? null : diseaseicd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.DiseCategoryID
     *
     * @return the value of disease.DiseCategoryID
     *
     * @mbggenerated
     */
    public Integer getDisecategoryid() {
        return disecategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.DiseCategoryID
     *
     * @param disecategoryid the value for disease.DiseCategoryID
     *
     * @mbggenerated
     */
    public void setDisecategoryid(Integer disecategoryid) {
        this.disecategoryid = disecategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.DelMark
     *
     * @return the value of disease.DelMark
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.DelMark
     *
     * @param delmark the value for disease.DelMark
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", diseasecode=").append(diseasecode);
        sb.append(", diseasename=").append(diseasename);
        sb.append(", diseaseicd=").append(diseaseicd);
        sb.append(", disecategoryid=").append(disecategoryid);
        sb.append(", delmark=").append(delmark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}