package org.neuedu.hisjava.model;

import java.io.Serializable;

public class DrugsDetailed implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drugsdetailed.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drugsdetailed.DrugsTempID
     *
     * @mbggenerated
     */
    private Integer drugstempid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drugsdetailed.DrugsID
     *
     * @mbggenerated
     */
    private Integer drugsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drugsdetailed.DrugsUsage
     *
     * @mbggenerated
     */
    private String drugsusage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drugsdetailed.Dosage
     *
     * @mbggenerated
     */
    private String dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drugsdetailed.Frequency
     *
     * @mbggenerated
     */
    private String frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drugsdetailed
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drugsdetailed.ID
     *
     * @return the value of drugsdetailed.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drugsdetailed.ID
     *
     * @param id the value for drugsdetailed.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drugsdetailed.DrugsTempID
     *
     * @return the value of drugsdetailed.DrugsTempID
     *
     * @mbggenerated
     */
    public Integer getDrugstempid() {
        return drugstempid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drugsdetailed.DrugsTempID
     *
     * @param drugstempid the value for drugsdetailed.DrugsTempID
     *
     * @mbggenerated
     */
    public void setDrugstempid(Integer drugstempid) {
        this.drugstempid = drugstempid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drugsdetailed.DrugsID
     *
     * @return the value of drugsdetailed.DrugsID
     *
     * @mbggenerated
     */
    public Integer getDrugsid() {
        return drugsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drugsdetailed.DrugsID
     *
     * @param drugsid the value for drugsdetailed.DrugsID
     *
     * @mbggenerated
     */
    public void setDrugsid(Integer drugsid) {
        this.drugsid = drugsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drugsdetailed.DrugsUsage
     *
     * @return the value of drugsdetailed.DrugsUsage
     *
     * @mbggenerated
     */
    public String getDrugsusage() {
        return drugsusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drugsdetailed.DrugsUsage
     *
     * @param drugsusage the value for drugsdetailed.DrugsUsage
     *
     * @mbggenerated
     */
    public void setDrugsusage(String drugsusage) {
        this.drugsusage = drugsusage == null ? null : drugsusage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drugsdetailed.Dosage
     *
     * @return the value of drugsdetailed.Dosage
     *
     * @mbggenerated
     */
    public String getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drugsdetailed.Dosage
     *
     * @param dosage the value for drugsdetailed.Dosage
     *
     * @mbggenerated
     */
    public void setDosage(String dosage) {
        this.dosage = dosage == null ? null : dosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drugsdetailed.Frequency
     *
     * @return the value of drugsdetailed.Frequency
     *
     * @mbggenerated
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drugsdetailed.Frequency
     *
     * @param frequency the value for drugsdetailed.Frequency
     *
     * @mbggenerated
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency == null ? null : frequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugsdetailed
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", drugstempid=").append(drugstempid);
        sb.append(", drugsid=").append(drugsid);
        sb.append(", drugsusage=").append(drugsusage);
        sb.append(", dosage=").append(dosage);
        sb.append(", frequency=").append(frequency);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}