package org.neuedu.hisjava.model;

import java.io.Serializable;

public class HerbalTempDetailed implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltempdetailed.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltempdetailed.HerbalTempID
     *
     * @mbggenerated
     */
    private Integer herbaltempid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltempdetailed.HerbalID
     *
     * @mbggenerated
     */
    private Integer herbalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltempdetailed.Dosage
     *
     * @mbggenerated
     */
    private String dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltempdetailed.Unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltempdetailed.Footnote
     *
     * @mbggenerated
     */
    private String footnote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table herbaltempdetailed
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltempdetailed.ID
     *
     * @return the value of herbaltempdetailed.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltempdetailed.ID
     *
     * @param id the value for herbaltempdetailed.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltempdetailed.HerbalTempID
     *
     * @return the value of herbaltempdetailed.HerbalTempID
     *
     * @mbggenerated
     */
    public Integer getHerbaltempid() {
        return herbaltempid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltempdetailed.HerbalTempID
     *
     * @param herbaltempid the value for herbaltempdetailed.HerbalTempID
     *
     * @mbggenerated
     */
    public void setHerbaltempid(Integer herbaltempid) {
        this.herbaltempid = herbaltempid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltempdetailed.HerbalID
     *
     * @return the value of herbaltempdetailed.HerbalID
     *
     * @mbggenerated
     */
    public Integer getHerbalid() {
        return herbalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltempdetailed.HerbalID
     *
     * @param herbalid the value for herbaltempdetailed.HerbalID
     *
     * @mbggenerated
     */
    public void setHerbalid(Integer herbalid) {
        this.herbalid = herbalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltempdetailed.Dosage
     *
     * @return the value of herbaltempdetailed.Dosage
     *
     * @mbggenerated
     */
    public String getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltempdetailed.Dosage
     *
     * @param dosage the value for herbaltempdetailed.Dosage
     *
     * @mbggenerated
     */
    public void setDosage(String dosage) {
        this.dosage = dosage == null ? null : dosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltempdetailed.Unit
     *
     * @return the value of herbaltempdetailed.Unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltempdetailed.Unit
     *
     * @param unit the value for herbaltempdetailed.Unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltempdetailed.Footnote
     *
     * @return the value of herbaltempdetailed.Footnote
     *
     * @mbggenerated
     */
    public String getFootnote() {
        return footnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltempdetailed.Footnote
     *
     * @param footnote the value for herbaltempdetailed.Footnote
     *
     * @mbggenerated
     */
    public void setFootnote(String footnote) {
        this.footnote = footnote == null ? null : footnote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaltempdetailed
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", herbaltempid=").append(herbaltempid);
        sb.append(", herbalid=").append(herbalid);
        sb.append(", dosage=").append(dosage);
        sb.append(", unit=").append(unit);
        sb.append(", footnote=").append(footnote);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}