package org.neuedu.hisjava.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class HerbalDetailed implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaldetailed.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaldetailed.HerbalPresID
     *
     * @mbggenerated
     */
    private Integer herbalpresid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaldetailed.HerbalID
     *
     * @mbggenerated
     */
    private Integer herbalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaldetailed.Dosage
     *
     * @mbggenerated
     */
    private String dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaldetailed.Price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaldetailed.Footnote
     *
     * @mbggenerated
     */
    private String footnote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table herbaldetailed
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaldetailed.ID
     *
     * @return the value of herbaldetailed.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaldetailed.ID
     *
     * @param id the value for herbaldetailed.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaldetailed.HerbalPresID
     *
     * @return the value of herbaldetailed.HerbalPresID
     *
     * @mbggenerated
     */
    public Integer getHerbalpresid() {
        return herbalpresid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaldetailed.HerbalPresID
     *
     * @param herbalpresid the value for herbaldetailed.HerbalPresID
     *
     * @mbggenerated
     */
    public void setHerbalpresid(Integer herbalpresid) {
        this.herbalpresid = herbalpresid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaldetailed.HerbalID
     *
     * @return the value of herbaldetailed.HerbalID
     *
     * @mbggenerated
     */
    public Integer getHerbalid() {
        return herbalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaldetailed.HerbalID
     *
     * @param herbalid the value for herbaldetailed.HerbalID
     *
     * @mbggenerated
     */
    public void setHerbalid(Integer herbalid) {
        this.herbalid = herbalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaldetailed.Dosage
     *
     * @return the value of herbaldetailed.Dosage
     *
     * @mbggenerated
     */
    public String getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaldetailed.Dosage
     *
     * @param dosage the value for herbaldetailed.Dosage
     *
     * @mbggenerated
     */
    public void setDosage(String dosage) {
        this.dosage = dosage == null ? null : dosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaldetailed.Price
     *
     * @return the value of herbaldetailed.Price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaldetailed.Price
     *
     * @param price the value for herbaldetailed.Price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaldetailed.Footnote
     *
     * @return the value of herbaldetailed.Footnote
     *
     * @mbggenerated
     */
    public String getFootnote() {
        return footnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaldetailed.Footnote
     *
     * @param footnote the value for herbaldetailed.Footnote
     *
     * @mbggenerated
     */
    public void setFootnote(String footnote) {
        this.footnote = footnote == null ? null : footnote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaldetailed
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", herbalpresid=").append(herbalpresid);
        sb.append(", herbalid=").append(herbalid);
        sb.append(", dosage=").append(dosage);
        sb.append(", price=").append(price);
        sb.append(", footnote=").append(footnote);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}