package org.neuedu.hisjava.model;

import java.io.Serializable;
import java.util.Date;

public class HerbalPrescription implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.MedicalID
     *
     * @mbggenerated
     */
    private Integer medicalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.RegistID
     *
     * @mbggenerated
     */
    private Integer registid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.UserID
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.PrescriptionName
     *
     * @mbggenerated
     */
    private String prescriptionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.CreationTime
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.PrescriptioType
     *
     * @mbggenerated
     */
    private String prescriptiotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.PayNumber
     *
     * @mbggenerated
     */
    private Integer paynumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.Frequency
     *
     * @mbggenerated
     */
    private String frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.DrugsUsage
     *
     * @mbggenerated
     */
    private String drugsusage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.Therapy
     *
     * @mbggenerated
     */
    private String therapy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.Detailed
     *
     * @mbggenerated
     */
    private String detailed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.Advice
     *
     * @mbggenerated
     */
    private String advice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbalprescription.State
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table herbalprescription
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.ID
     *
     * @return the value of herbalprescription.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.ID
     *
     * @param id the value for herbalprescription.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.MedicalID
     *
     * @return the value of herbalprescription.MedicalID
     *
     * @mbggenerated
     */
    public Integer getMedicalid() {
        return medicalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.MedicalID
     *
     * @param medicalid the value for herbalprescription.MedicalID
     *
     * @mbggenerated
     */
    public void setMedicalid(Integer medicalid) {
        this.medicalid = medicalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.RegistID
     *
     * @return the value of herbalprescription.RegistID
     *
     * @mbggenerated
     */
    public Integer getRegistid() {
        return registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.RegistID
     *
     * @param registid the value for herbalprescription.RegistID
     *
     * @mbggenerated
     */
    public void setRegistid(Integer registid) {
        this.registid = registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.UserID
     *
     * @return the value of herbalprescription.UserID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.UserID
     *
     * @param userid the value for herbalprescription.UserID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.PrescriptionName
     *
     * @return the value of herbalprescription.PrescriptionName
     *
     * @mbggenerated
     */
    public String getPrescriptionname() {
        return prescriptionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.PrescriptionName
     *
     * @param prescriptionname the value for herbalprescription.PrescriptionName
     *
     * @mbggenerated
     */
    public void setPrescriptionname(String prescriptionname) {
        this.prescriptionname = prescriptionname == null ? null : prescriptionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.CreationTime
     *
     * @return the value of herbalprescription.CreationTime
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.CreationTime
     *
     * @param creationtime the value for herbalprescription.CreationTime
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.PrescriptioType
     *
     * @return the value of herbalprescription.PrescriptioType
     *
     * @mbggenerated
     */
    public String getPrescriptiotype() {
        return prescriptiotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.PrescriptioType
     *
     * @param prescriptiotype the value for herbalprescription.PrescriptioType
     *
     * @mbggenerated
     */
    public void setPrescriptiotype(String prescriptiotype) {
        this.prescriptiotype = prescriptiotype == null ? null : prescriptiotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.PayNumber
     *
     * @return the value of herbalprescription.PayNumber
     *
     * @mbggenerated
     */
    public Integer getPaynumber() {
        return paynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.PayNumber
     *
     * @param paynumber the value for herbalprescription.PayNumber
     *
     * @mbggenerated
     */
    public void setPaynumber(Integer paynumber) {
        this.paynumber = paynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.Frequency
     *
     * @return the value of herbalprescription.Frequency
     *
     * @mbggenerated
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.Frequency
     *
     * @param frequency the value for herbalprescription.Frequency
     *
     * @mbggenerated
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency == null ? null : frequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.DrugsUsage
     *
     * @return the value of herbalprescription.DrugsUsage
     *
     * @mbggenerated
     */
    public String getDrugsusage() {
        return drugsusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.DrugsUsage
     *
     * @param drugsusage the value for herbalprescription.DrugsUsage
     *
     * @mbggenerated
     */
    public void setDrugsusage(String drugsusage) {
        this.drugsusage = drugsusage == null ? null : drugsusage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.Therapy
     *
     * @return the value of herbalprescription.Therapy
     *
     * @mbggenerated
     */
    public String getTherapy() {
        return therapy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.Therapy
     *
     * @param therapy the value for herbalprescription.Therapy
     *
     * @mbggenerated
     */
    public void setTherapy(String therapy) {
        this.therapy = therapy == null ? null : therapy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.Detailed
     *
     * @return the value of herbalprescription.Detailed
     *
     * @mbggenerated
     */
    public String getDetailed() {
        return detailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.Detailed
     *
     * @param detailed the value for herbalprescription.Detailed
     *
     * @mbggenerated
     */
    public void setDetailed(String detailed) {
        this.detailed = detailed == null ? null : detailed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.Advice
     *
     * @return the value of herbalprescription.Advice
     *
     * @mbggenerated
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.Advice
     *
     * @param advice the value for herbalprescription.Advice
     *
     * @mbggenerated
     */
    public void setAdvice(String advice) {
        this.advice = advice == null ? null : advice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbalprescription.State
     *
     * @return the value of herbalprescription.State
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbalprescription.State
     *
     * @param state the value for herbalprescription.State
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbalprescription
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", medicalid=").append(medicalid);
        sb.append(", registid=").append(registid);
        sb.append(", userid=").append(userid);
        sb.append(", prescriptionname=").append(prescriptionname);
        sb.append(", creationtime=").append(creationtime);
        sb.append(", prescriptiotype=").append(prescriptiotype);
        sb.append(", paynumber=").append(paynumber);
        sb.append(", frequency=").append(frequency);
        sb.append(", drugsusage=").append(drugsusage);
        sb.append(", therapy=").append(therapy);
        sb.append(", detailed=").append(detailed);
        sb.append(", advice=").append(advice);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}