package org.neuedu.hisjava.model;

import java.io.Serializable;
import java.util.Date;

public class HerbalTemplate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.DoctorID
     *
     * @mbggenerated
     */
    private Integer doctorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.CreationTime
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.PrescriptioType
     *
     * @mbggenerated
     */
    private String prescriptiotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.PayNumber
     *
     * @mbggenerated
     */
    private Integer paynumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.DrugsUsage
     *
     * @mbggenerated
     */
    private String drugsusage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.Therapy
     *
     * @mbggenerated
     */
    private String therapy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.Detailed
     *
     * @mbggenerated
     */
    private String detailed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.Advice
     *
     * @mbggenerated
     */
    private String advice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.Scope
     *
     * @mbggenerated
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column herbaltemplate.DelMark
     *
     * @mbggenerated
     */
    private Integer delmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table herbaltemplate
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.ID
     *
     * @return the value of herbaltemplate.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.ID
     *
     * @param id the value for herbaltemplate.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.Name
     *
     * @return the value of herbaltemplate.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.Name
     *
     * @param name the value for herbaltemplate.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.DoctorID
     *
     * @return the value of herbaltemplate.DoctorID
     *
     * @mbggenerated
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.DoctorID
     *
     * @param doctorid the value for herbaltemplate.DoctorID
     *
     * @mbggenerated
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.CreationTime
     *
     * @return the value of herbaltemplate.CreationTime
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.CreationTime
     *
     * @param creationtime the value for herbaltemplate.CreationTime
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.PrescriptioType
     *
     * @return the value of herbaltemplate.PrescriptioType
     *
     * @mbggenerated
     */
    public String getPrescriptiotype() {
        return prescriptiotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.PrescriptioType
     *
     * @param prescriptiotype the value for herbaltemplate.PrescriptioType
     *
     * @mbggenerated
     */
    public void setPrescriptiotype(String prescriptiotype) {
        this.prescriptiotype = prescriptiotype == null ? null : prescriptiotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.PayNumber
     *
     * @return the value of herbaltemplate.PayNumber
     *
     * @mbggenerated
     */
    public Integer getPaynumber() {
        return paynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.PayNumber
     *
     * @param paynumber the value for herbaltemplate.PayNumber
     *
     * @mbggenerated
     */
    public void setPaynumber(Integer paynumber) {
        this.paynumber = paynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.DrugsUsage
     *
     * @return the value of herbaltemplate.DrugsUsage
     *
     * @mbggenerated
     */
    public String getDrugsusage() {
        return drugsusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.DrugsUsage
     *
     * @param drugsusage the value for herbaltemplate.DrugsUsage
     *
     * @mbggenerated
     */
    public void setDrugsusage(String drugsusage) {
        this.drugsusage = drugsusage == null ? null : drugsusage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.Therapy
     *
     * @return the value of herbaltemplate.Therapy
     *
     * @mbggenerated
     */
    public String getTherapy() {
        return therapy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.Therapy
     *
     * @param therapy the value for herbaltemplate.Therapy
     *
     * @mbggenerated
     */
    public void setTherapy(String therapy) {
        this.therapy = therapy == null ? null : therapy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.Detailed
     *
     * @return the value of herbaltemplate.Detailed
     *
     * @mbggenerated
     */
    public String getDetailed() {
        return detailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.Detailed
     *
     * @param detailed the value for herbaltemplate.Detailed
     *
     * @mbggenerated
     */
    public void setDetailed(String detailed) {
        this.detailed = detailed == null ? null : detailed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.Advice
     *
     * @return the value of herbaltemplate.Advice
     *
     * @mbggenerated
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.Advice
     *
     * @param advice the value for herbaltemplate.Advice
     *
     * @mbggenerated
     */
    public void setAdvice(String advice) {
        this.advice = advice == null ? null : advice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.Scope
     *
     * @return the value of herbaltemplate.Scope
     *
     * @mbggenerated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.Scope
     *
     * @param scope the value for herbaltemplate.Scope
     *
     * @mbggenerated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column herbaltemplate.DelMark
     *
     * @return the value of herbaltemplate.DelMark
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column herbaltemplate.DelMark
     *
     * @param delmark the value for herbaltemplate.DelMark
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table herbaltemplate
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", doctorid=").append(doctorid);
        sb.append(", creationtime=").append(creationtime);
        sb.append(", prescriptiotype=").append(prescriptiotype);
        sb.append(", paynumber=").append(paynumber);
        sb.append(", drugsusage=").append(drugsusage);
        sb.append(", therapy=").append(therapy);
        sb.append(", detailed=").append(detailed);
        sb.append(", advice=").append(advice);
        sb.append(", scope=").append(scope);
        sb.append(", delmark=").append(delmark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}