package org.neuedu.hisjava.model;

import java.io.Serializable;
import java.util.Date;

public class MedicalDisease implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicaldisease.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicaldisease.MedicalID
     *
     * @mbggenerated
     */
    private Integer medicalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicaldisease.RegistID
     *
     * @mbggenerated
     */
    private Integer registid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicaldisease.DiseaseID
     *
     * @mbggenerated
     */
    private Integer diseaseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicaldisease.DiagnoseType
     *
     * @mbggenerated
     */
    private Integer diagnosetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicaldisease.GetSiskDate
     *
     * @mbggenerated
     */
    private Date getsiskdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicaldisease.DiagnoseCate
     *
     * @mbggenerated
     */
    private Integer diagnosecate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medicaldisease
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicaldisease.ID
     *
     * @return the value of medicaldisease.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicaldisease.ID
     *
     * @param id the value for medicaldisease.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicaldisease.MedicalID
     *
     * @return the value of medicaldisease.MedicalID
     *
     * @mbggenerated
     */
    public Integer getMedicalid() {
        return medicalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicaldisease.MedicalID
     *
     * @param medicalid the value for medicaldisease.MedicalID
     *
     * @mbggenerated
     */
    public void setMedicalid(Integer medicalid) {
        this.medicalid = medicalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicaldisease.RegistID
     *
     * @return the value of medicaldisease.RegistID
     *
     * @mbggenerated
     */
    public Integer getRegistid() {
        return registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicaldisease.RegistID
     *
     * @param registid the value for medicaldisease.RegistID
     *
     * @mbggenerated
     */
    public void setRegistid(Integer registid) {
        this.registid = registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicaldisease.DiseaseID
     *
     * @return the value of medicaldisease.DiseaseID
     *
     * @mbggenerated
     */
    public Integer getDiseaseid() {
        return diseaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicaldisease.DiseaseID
     *
     * @param diseaseid the value for medicaldisease.DiseaseID
     *
     * @mbggenerated
     */
    public void setDiseaseid(Integer diseaseid) {
        this.diseaseid = diseaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicaldisease.DiagnoseType
     *
     * @return the value of medicaldisease.DiagnoseType
     *
     * @mbggenerated
     */
    public Integer getDiagnosetype() {
        return diagnosetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicaldisease.DiagnoseType
     *
     * @param diagnosetype the value for medicaldisease.DiagnoseType
     *
     * @mbggenerated
     */
    public void setDiagnosetype(Integer diagnosetype) {
        this.diagnosetype = diagnosetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicaldisease.GetSiskDate
     *
     * @return the value of medicaldisease.GetSiskDate
     *
     * @mbggenerated
     */
    public Date getGetsiskdate() {
        return getsiskdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicaldisease.GetSiskDate
     *
     * @param getsiskdate the value for medicaldisease.GetSiskDate
     *
     * @mbggenerated
     */
    public void setGetsiskdate(Date getsiskdate) {
        this.getsiskdate = getsiskdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicaldisease.DiagnoseCate
     *
     * @return the value of medicaldisease.DiagnoseCate
     *
     * @mbggenerated
     */
    public Integer getDiagnosecate() {
        return diagnosecate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicaldisease.DiagnoseCate
     *
     * @param diagnosecate the value for medicaldisease.DiagnoseCate
     *
     * @mbggenerated
     */
    public void setDiagnosecate(Integer diagnosecate) {
        this.diagnosecate = diagnosecate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicaldisease
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", medicalid=").append(medicalid);
        sb.append(", registid=").append(registid);
        sb.append(", diseaseid=").append(diseaseid);
        sb.append(", diagnosetype=").append(diagnosetype);
        sb.append(", getsiskdate=").append(getsiskdate);
        sb.append(", diagnosecate=").append(diagnosecate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}