package org.neuedu.hisjava.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Patientcosts implements Serializable {
    private Register register;
    public Register getRegister() {
        return register;
    }

    public void setRegister(Register register) {
        this.register = register;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.RegistID
     *
     * @mbggenerated
     */
    private Integer registid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.InvoiceID
     *
     * @mbggenerated
     */
    private Integer invoiceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.ItemID
     *
     * @mbggenerated
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.ItemType
     *
     * @mbggenerated
     */
    private Integer itemtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.Price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.Amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.DeptID
     *
     * @mbggenerated
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.Createtime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd hh:mm:ss",timezone = "Asia/Shanghai")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.CreateOperID
     *
     * @mbggenerated
     */
    private Integer createoperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.PayTime
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd hh:mm:ss",timezone = "Asia/Shanghai")
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.RegisterID
     *
     * @mbggenerated
     */
    private Integer registerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.FeeType
     *
     * @mbggenerated
     */
    private Integer feetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientcosts.BackID
     *
     * @mbggenerated
     */
    private Integer backid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patientcosts
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.ID
     *
     * @return the value of patientcosts.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.ID
     *
     * @param id the value for patientcosts.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.RegistID
     *
     * @return the value of patientcosts.RegistID
     *
     * @mbggenerated
     */
    public Integer getRegistid() {
        return registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.RegistID
     *
     * @param registid the value for patientcosts.RegistID
     *
     * @mbggenerated
     */
    public void setRegistid(Integer registid) {
        this.registid = registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.InvoiceID
     *
     * @return the value of patientcosts.InvoiceID
     *
     * @mbggenerated
     */
    public Integer getInvoiceid() {
        return invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.InvoiceID
     *
     * @param invoiceid the value for patientcosts.InvoiceID
     *
     * @mbggenerated
     */
    public void setInvoiceid(Integer invoiceid) {
        this.invoiceid = invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.ItemID
     *
     * @return the value of patientcosts.ItemID
     *
     * @mbggenerated
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.ItemID
     *
     * @param itemid the value for patientcosts.ItemID
     *
     * @mbggenerated
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.ItemType
     *
     * @return the value of patientcosts.ItemType
     *
     * @mbggenerated
     */
    public Integer getItemtype() {
        return itemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.ItemType
     *
     * @param itemtype the value for patientcosts.ItemType
     *
     * @mbggenerated
     */
    public void setItemtype(Integer itemtype) {
        this.itemtype = itemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.Name
     *
     * @return the value of patientcosts.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.Name
     *
     * @param name the value for patientcosts.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.Price
     *
     * @return the value of patientcosts.Price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.Price
     *
     * @param price the value for patientcosts.Price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.Amount
     *
     * @return the value of patientcosts.Amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.Amount
     *
     * @param amount the value for patientcosts.Amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.DeptID
     *
     * @return the value of patientcosts.DeptID
     *
     * @mbggenerated
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.DeptID
     *
     * @param deptid the value for patientcosts.DeptID
     *
     * @mbggenerated
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.Createtime
     *
     * @return the value of patientcosts.Createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.Createtime
     *
     * @param createtime the value for patientcosts.Createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.CreateOperID
     *
     * @return the value of patientcosts.CreateOperID
     *
     * @mbggenerated
     */
    public Integer getCreateoperid() {
        return createoperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.CreateOperID
     *
     * @param createoperid the value for patientcosts.CreateOperID
     *
     * @mbggenerated
     */
    public void setCreateoperid(Integer createoperid) {
        this.createoperid = createoperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.PayTime
     *
     * @return the value of patientcosts.PayTime
     *
     * @mbggenerated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.PayTime
     *
     * @param paytime the value for patientcosts.PayTime
     *
     * @mbggenerated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.RegisterID
     *
     * @return the value of patientcosts.RegisterID
     *
     * @mbggenerated
     */
    public Integer getRegisterid() {
        return registerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.RegisterID
     *
     * @param registerid the value for patientcosts.RegisterID
     *
     * @mbggenerated
     */
    public void setRegisterid(Integer registerid) {
        this.registerid = registerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.FeeType
     *
     * @return the value of patientcosts.FeeType
     *
     * @mbggenerated
     */
    public Integer getFeetype() {
        return feetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.FeeType
     *
     * @param feetype the value for patientcosts.FeeType
     *
     * @mbggenerated
     */
    public void setFeetype(Integer feetype) {
        this.feetype = feetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientcosts.BackID
     *
     * @return the value of patientcosts.BackID
     *
     * @mbggenerated
     */
    public Integer getBackid() {
        return backid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientcosts.BackID
     *
     * @param backid the value for patientcosts.BackID
     *
     * @mbggenerated
     */
    public void setBackid(Integer backid) {
        this.backid = backid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientcosts
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", registid=").append(registid);
        sb.append(", invoiceid=").append(invoiceid);
        sb.append(", itemid=").append(itemid);
        sb.append(", itemtype=").append(itemtype);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", amount=").append(amount);
        sb.append(", deptid=").append(deptid);
        sb.append(", createtime=").append(createtime);
        sb.append(", createoperid=").append(createoperid);
        sb.append(", paytime=").append(paytime);
        sb.append(", registerid=").append(registerid);
        sb.append(", feetype=").append(feetype);
        sb.append(", backid=").append(backid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}