package org.neuedu.hisjava.model;

import java.io.Serializable;
import java.util.Date;

public class Prescription implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.MedicalID
     *
     * @mbggenerated
     */
    private Integer medicalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.RegistID
     *
     * @mbggenerated
     */
    private Integer registid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.UserID
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.PrescriptionName
     *
     * @mbggenerated
     */
    private String prescriptionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.PrescriptionTime
     *
     * @mbggenerated
     */
    private Date prescriptiontime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.PrescriptionState
     *
     * @mbggenerated
     */
    private Integer prescriptionstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prescription
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ID
     *
     * @return the value of prescription.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ID
     *
     * @param id the value for prescription.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.MedicalID
     *
     * @return the value of prescription.MedicalID
     *
     * @mbggenerated
     */
    public Integer getMedicalid() {
        return medicalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.MedicalID
     *
     * @param medicalid the value for prescription.MedicalID
     *
     * @mbggenerated
     */
    public void setMedicalid(Integer medicalid) {
        this.medicalid = medicalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.RegistID
     *
     * @return the value of prescription.RegistID
     *
     * @mbggenerated
     */
    public Integer getRegistid() {
        return registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.RegistID
     *
     * @param registid the value for prescription.RegistID
     *
     * @mbggenerated
     */
    public void setRegistid(Integer registid) {
        this.registid = registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.UserID
     *
     * @return the value of prescription.UserID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.UserID
     *
     * @param userid the value for prescription.UserID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.PrescriptionName
     *
     * @return the value of prescription.PrescriptionName
     *
     * @mbggenerated
     */
    public String getPrescriptionname() {
        return prescriptionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.PrescriptionName
     *
     * @param prescriptionname the value for prescription.PrescriptionName
     *
     * @mbggenerated
     */
    public void setPrescriptionname(String prescriptionname) {
        this.prescriptionname = prescriptionname == null ? null : prescriptionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.PrescriptionTime
     *
     * @return the value of prescription.PrescriptionTime
     *
     * @mbggenerated
     */
    public Date getPrescriptiontime() {
        return prescriptiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.PrescriptionTime
     *
     * @param prescriptiontime the value for prescription.PrescriptionTime
     *
     * @mbggenerated
     */
    public void setPrescriptiontime(Date prescriptiontime) {
        this.prescriptiontime = prescriptiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.PrescriptionState
     *
     * @return the value of prescription.PrescriptionState
     *
     * @mbggenerated
     */
    public Integer getPrescriptionstate() {
        return prescriptionstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.PrescriptionState
     *
     * @param prescriptionstate the value for prescription.PrescriptionState
     *
     * @mbggenerated
     */
    public void setPrescriptionstate(Integer prescriptionstate) {
        this.prescriptionstate = prescriptionstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", medicalid=").append(medicalid);
        sb.append(", registid=").append(registid);
        sb.append(", userid=").append(userid);
        sb.append(", prescriptionname=").append(prescriptionname);
        sb.append(", prescriptiontime=").append(prescriptiontime);
        sb.append(", prescriptionstate=").append(prescriptionstate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}