package org.neuedu.hisjava.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class PrescriptionDetailed implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptiondetailed.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptiondetailed.PrescriptionID
     *
     * @mbggenerated
     */
    private Integer prescriptionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptiondetailed.DrugsID
     *
     * @mbggenerated
     */
    private Integer drugsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptiondetailed.DrugsUsage
     *
     * @mbggenerated
     */
    private String drugsusage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptiondetailed.Dosage
     *
     * @mbggenerated
     */
    private String dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptiondetailed.Frequency
     *
     * @mbggenerated
     */
    private String frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptiondetailed.Amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptiondetailed.State
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prescriptiondetailed
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptiondetailed.ID
     *
     * @return the value of prescriptiondetailed.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptiondetailed.ID
     *
     * @param id the value for prescriptiondetailed.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptiondetailed.PrescriptionID
     *
     * @return the value of prescriptiondetailed.PrescriptionID
     *
     * @mbggenerated
     */
    public Integer getPrescriptionid() {
        return prescriptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptiondetailed.PrescriptionID
     *
     * @param prescriptionid the value for prescriptiondetailed.PrescriptionID
     *
     * @mbggenerated
     */
    public void setPrescriptionid(Integer prescriptionid) {
        this.prescriptionid = prescriptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptiondetailed.DrugsID
     *
     * @return the value of prescriptiondetailed.DrugsID
     *
     * @mbggenerated
     */
    public Integer getDrugsid() {
        return drugsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptiondetailed.DrugsID
     *
     * @param drugsid the value for prescriptiondetailed.DrugsID
     *
     * @mbggenerated
     */
    public void setDrugsid(Integer drugsid) {
        this.drugsid = drugsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptiondetailed.DrugsUsage
     *
     * @return the value of prescriptiondetailed.DrugsUsage
     *
     * @mbggenerated
     */
    public String getDrugsusage() {
        return drugsusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptiondetailed.DrugsUsage
     *
     * @param drugsusage the value for prescriptiondetailed.DrugsUsage
     *
     * @mbggenerated
     */
    public void setDrugsusage(String drugsusage) {
        this.drugsusage = drugsusage == null ? null : drugsusage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptiondetailed.Dosage
     *
     * @return the value of prescriptiondetailed.Dosage
     *
     * @mbggenerated
     */
    public String getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptiondetailed.Dosage
     *
     * @param dosage the value for prescriptiondetailed.Dosage
     *
     * @mbggenerated
     */
    public void setDosage(String dosage) {
        this.dosage = dosage == null ? null : dosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptiondetailed.Frequency
     *
     * @return the value of prescriptiondetailed.Frequency
     *
     * @mbggenerated
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptiondetailed.Frequency
     *
     * @param frequency the value for prescriptiondetailed.Frequency
     *
     * @mbggenerated
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency == null ? null : frequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptiondetailed.Amount
     *
     * @return the value of prescriptiondetailed.Amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptiondetailed.Amount
     *
     * @param amount the value for prescriptiondetailed.Amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptiondetailed.State
     *
     * @return the value of prescriptiondetailed.State
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptiondetailed.State
     *
     * @param state the value for prescriptiondetailed.State
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescriptiondetailed
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", prescriptionid=").append(prescriptionid);
        sb.append(", drugsid=").append(drugsid);
        sb.append(", drugsusage=").append(drugsusage);
        sb.append(", dosage=").append(dosage);
        sb.append(", frequency=").append(frequency);
        sb.append(", amount=").append(amount);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}