package org.neuedu.hisjava.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Registlevel implements Serializable {

    private Integer id;
    private String registcode;
    private String registname;
    private Integer sequenceno;
    private BigDecimal registfee;
    private Integer registquota;
    private Integer delmark;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.ID
     *
     * @return the value of registlevel.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.ID
     *
     * @param id the value for registlevel.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.RegistCode
     *
     * @return the value of registlevel.RegistCode
     *
     * @mbggenerated
     */
    public String getRegistcode() {
        return registcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.RegistCode
     *
     * @param registcode the value for registlevel.RegistCode
     *
     * @mbggenerated
     */
    public void setRegistcode(String registcode) {
        this.registcode = registcode == null ? null : registcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.RegistName
     *
     * @return the value of registlevel.RegistName
     *
     * @mbggenerated
     */
    public String getRegistname() {
        return registname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.RegistName
     *
     * @param registname the value for registlevel.RegistName
     *
     * @mbggenerated
     */
    public void setRegistname(String registname) {
        this.registname = registname == null ? null : registname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.SequenceNo
     *
     * @return the value of registlevel.SequenceNo
     *
     * @mbggenerated
     */
    public Integer getSequenceno() {
        return sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.SequenceNo
     *
     * @param sequenceno the value for registlevel.SequenceNo
     *
     * @mbggenerated
     */
    public void setSequenceno(Integer sequenceno) {
        this.sequenceno = sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.RegistFee
     *
     * @return the value of registlevel.RegistFee
     *
     * @mbggenerated
     */
    public BigDecimal getRegistfee() {
        return registfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.RegistFee
     *
     * @param registfee the value for registlevel.RegistFee
     *
     * @mbggenerated
     */
    public void setRegistfee(BigDecimal registfee) {
        this.registfee = registfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.RegistQuota
     *
     * @return the value of registlevel.RegistQuota
     *
     * @mbggenerated
     */
    public Integer getRegistquota() {
        return registquota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.RegistQuota
     *
     * @param registquota the value for registlevel.RegistQuota
     *
     * @mbggenerated
     */
    public void setRegistquota(Integer registquota) {
        this.registquota = registquota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.DelMark
     *
     * @return the value of registlevel.DelMark
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.DelMark
     *
     * @param delmark the value for registlevel.DelMark
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", registcode=").append(registcode);
        sb.append(", registname=").append(registname);
        sb.append(", sequenceno=").append(sequenceno);
        sb.append(", registfee=").append(registfee);
        sb.append(", registquota=").append(registquota);
        sb.append(", delmark=").append(delmark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}