package org.neuedu.hisjava.model;

import java.io.Serializable;

public class Settlecategory implements Serializable {

    private Integer id;
    private String settlecode;
    private String settlename;
    private Integer sequenceno;
    private Integer delmark;
    private static final long serialVersionUID = 1L;
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.ID
     *
     * @param id the value for settlecategory.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.SettleCode
     *
     * @return the value of settlecategory.SettleCode
     *
     * @mbggenerated
     */
    public String getSettlecode() {
        return settlecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.SettleCode
     *
     * @param settlecode the value for settlecategory.SettleCode
     *
     * @mbggenerated
     */
    public void setSettlecode(String settlecode) {
        this.settlecode = settlecode == null ? null : settlecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.SettleName
     *
     * @return the value of settlecategory.SettleName
     *
     * @mbggenerated
     */
    public String getSettlename() {
        return settlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.SettleName
     *
     * @param settlename the value for settlecategory.SettleName
     *
     * @mbggenerated
     */
    public void setSettlename(String settlename) {
        this.settlename = settlename == null ? null : settlename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.SequenceNo
     *
     * @return the value of settlecategory.SequenceNo
     *
     * @mbggenerated
     */
    public Integer getSequenceno() {
        return sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.SequenceNo
     *
     * @param sequenceno the value for settlecategory.SequenceNo
     *
     * @mbggenerated
     */
    public void setSequenceno(Integer sequenceno) {
        this.sequenceno = sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.DelMark
     *
     * @return the value of settlecategory.DelMark
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.DelMark
     *
     * @param delmark the value for settlecategory.DelMark
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlecategory
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", settlecode=").append(settlecode);
        sb.append(", settlename=").append(settlename);
        sb.append(", sequenceno=").append(sequenceno);
        sb.append(", delmark=").append(delmark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}