package org.neuedu.hisjava.model;

import java.io.Serializable;

public class User implements Serializable {
    private Integer id;
    private String username;
    private String password;
    private String realname;
    private Integer usetype;
    private Integer doctitleid;
    private String isscheduling;
    private Integer deptid;
    private Integer registleid;
    private Integer delmark;
    private static final long serialVersionUID = 1L;
    private Department department;
    private Constantitem constantitem;

    public Registlevel getRegistlevel() {
        return registlevel;
    }

    public void setRegistlevel(Registlevel registlevel) {
        this.registlevel = registlevel;
    }

    private Registlevel registlevel;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public Constantitem getConstantitem() {
        return constantitem;
    }

    public void setConstantitem(Constantitem constantitem) {
        this.constantitem = constantitem;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserName
     *
     * @return the value of user.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserName
     *
     * @param username the value for user.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password
     *
     * @return the value of user.Password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password
     *
     * @param password the value for user.Password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.RealName
     *
     * @return the value of user.RealName
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.RealName
     *
     * @param realname the value for user.RealName
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UseType
     *
     * @return the value of user.UseType
     *
     * @mbggenerated
     */
    public Integer getUsetype() {
        return usetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UseType
     *
     * @param usetype the value for user.UseType
     *
     * @mbggenerated
     */
    public void setUsetype(Integer usetype) {
        this.usetype = usetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DocTitleID
     *
     * @return the value of user.DocTitleID
     *
     * @mbggenerated
     */
    public Integer getDoctitleid() {
        return doctitleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DocTitleID
     *
     * @param doctitleid the value for user.DocTitleID
     *
     * @mbggenerated
     */
    public void setDoctitleid(Integer doctitleid) {
        this.doctitleid = doctitleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IsScheduling
     *
     * @return the value of user.IsScheduling
     *
     * @mbggenerated
     */
    public String getIsscheduling() {
        return isscheduling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IsScheduling
     *
     * @param isscheduling the value for user.IsScheduling
     *
     * @mbggenerated
     */
    public void setIsscheduling(String isscheduling) {
        this.isscheduling = isscheduling == null ? null : isscheduling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DeptID
     *
     * @return the value of user.DeptID
     *
     * @mbggenerated
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DeptID
     *
     * @param deptid the value for user.DeptID
     *
     * @mbggenerated
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.RegistLeID
     *
     * @return the value of user.RegistLeID
     *
     * @mbggenerated
     */
    public Integer getRegistleid() {
        return registleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.RegistLeID
     *
     * @param registleid the value for user.RegistLeID
     *
     * @mbggenerated
     */
    public void setRegistleid(Integer registleid) {
        this.registleid = registleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DelMark
     *
     * @return the value of user.DelMark
     *
     * @mbggenerated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DelMark
     *
     * @param delmark the value for user.DelMark
     *
     * @mbggenerated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", realname=").append(realname);
        sb.append(", usetype=").append(usetype);
        sb.append(", doctitleid=").append(doctitleid);
        sb.append(", isscheduling=").append(isscheduling);
        sb.append(", deptid=").append(deptid);
        sb.append(", registleid=").append(registleid);
        sb.append(", delmark=").append(delmark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}